# Generated by Django 5.2.5 on 2025-08-30 02:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("arabica", "Arábica"),
                            ("robusta", "Robusta"),
                            ("blend", "Blend"),
                        ],
                        default="arabica",
                        max_length=20,
                    ),
                ),
                ("stock_kg", models.FloatField(default=0)),
                ("min_stock_kg", models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "delivery_speed",
                    models.CharField(
                        choices=[("fast", "Rápida"), ("economy", "Económica")],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="received", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60, unique=True)),
                (
                    "coffee_type",
                    models.CharField(
                        choices=[
                            ("arabica", "Arábica"),
                            ("robusta", "Robusta"),
                            ("blend", "Blend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("qty_kg", models.FloatField()),
                ("cupping_score", models.FloatField(blank=True, null=True)),
                ("mfg_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("roast", "Tostado"),
                            ("grind", "Molido"),
                            ("pack", "Empaque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_unit", models.CharField(max_length=120)),
                ("planned_kg", models.FloatField()),
                ("progress", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RawGrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("arabica", "Arábica"),
                            ("robusta", "Robusta"),
                            ("blend", "Blend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(blank=True, max_length=120)),
                ("lot_code", models.CharField(max_length=60, unique=True)),
                ("quantity_kg", models.FloatField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.TextField(blank=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("received_confirmed", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_kg", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.order",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("supplier", models.CharField(max_length=120)),
                ("qty_kg", models.FloatField()),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
