# Generated by Django 5.2.5 on 2025-10-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("TO", "Tostado"),
                            ("MO", "Molido"),
                            ("EN", "Envasado"),
                            ("CO", "Completado"),
                        ],
                        default="TO",
                        max_length=2,
                    ),
                ),
                ("assigned_unit", models.CharField(max_length=100)),
                ("planned_kg", models.FloatField()),
                ("progress", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_stage_index", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "coffee_type",
                    models.CharField(
                        choices=[("AR", "Arábica"), ("RO", "Robusta"), ("BL", "Blend")],
                        max_length=2,
                    ),
                ),
                ("qty_kg", models.FloatField()),
                ("cupping_score", models.FloatField(blank=True, null=True)),
                ("mfg_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "production_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="production.productiontask",
                    ),
                ),
            ],
        ),
    ]
