# Generated by Django 5.2.5 on 2025-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiontask",
            name="current_stage_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productiontask",
            name="stage",
            field=models.CharField(
                choices=[
                    ("TO", "Tostado"),
                    ("MO", "Molido"),
                    ("EN", "Envasado"),
                    ("CO", "Completado"),
                ],
                default="TO",
                max_length=2,
            ),
        ),
    ]
