# Generated by Django 5.2.5 on 2025-09-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_productiontask_current_stage_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productiontask",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
