# Generated by Django 5.2.5 on 2025-10-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("AR", "Arábica"), ("RO", "Robusta"), ("BL", "Blend")],
                        max_length=2,
                    ),
                ),
                ("stock_kg", models.FloatField(default=0)),
                ("min_stock_kg", models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="RawGrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("AR", "Arábica"), ("RO", "Robusta"), ("BL", "Blend")],
                        max_length=2,
                    ),
                ),
                ("origin", models.CharField(max_length=100)),
                ("lot_code", models.CharField(max_length=50, unique=True)),
                ("quantity_kg", models.FloatField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("supplier", models.CharField(max_length=200)),
                ("qty_kg", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ORDERED", "Ordenado"),
                            ("RECEIVED", "Recibido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
    ]
